Document: raspicam
Title: Debian raspicam Manual
Author: <insert document author here>
Abstract: This manual describes what raspicam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/raspicam/raspicam.sgml.gz

Format: postscript
Files: /usr/share/doc/raspicam/raspicam.ps.gz

Format: text
Files: /usr/share/doc/raspicam/raspicam.text.gz

Format: HTML
Index: /usr/share/doc/raspicam/html/index.html
Files: /usr/share/doc/raspicam/html/*.html
