Document: cvblob
Title: Debian cvblob Manual
Author: <insert document author here>
Abstract: This manual describes what cvblob is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cvblob/cvblob.sgml.gz

Format: postscript
Files: /usr/share/doc/cvblob/cvblob.ps.gz

Format: text
Files: /usr/share/doc/cvblob/cvblob.text.gz

Format: HTML
Index: /usr/share/doc/cvblob/html/index.html
Files: /usr/share/doc/cvblob/html/*.html
